version: "3.9"
services:
  db:
    image: postgres:16
    container_name: zippotify-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zc
      POSTGRES_PASSWORD: zcpass
      POSTGRES_DB: zippotify
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zc -d zippotify"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: